fixes

diff --git a/root/etc/s6-overlay/s6-rc.d/service-proton/run b/root/etc/s6-overlay/s6-rc.d/service-proton/run
--- a/root/etc/s6-overlay/s6-rc.d/service-proton/run
+++ b/root/etc/s6-overlay/s6-rc.d/service-proton/run
@@ -4,23 +4,25 @@
 umask "${UMASK}"
 
 vpn_gw=$(grep -P -o -m 1 '(?<=^Address)(\s{0,})[^/]+' < "${CONFIG_DIR}/wireguard/${VPN_CONF}.conf"| sed -e 's~^[=\ ]*~~')
+vpn_gw="${vpn_gw%.*}.1"
 
 while true; do
-    if ! natpmpc -g "${vpn_gw%.*}.1" &> /dev/null; then
-        echo "[WARNING] ProtonVPN endpoint \"${vpn_gw%.*}.1\" does not support port forwarding!"
+    if ! natpmpc -g "${vpn_gw}" &> /dev/null; then
+        echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN endpoint \"${vpn_gw%.*}.1\" does not support port forwarding!"
     else
-        port=$(natpmpc -g "${vpn_gw%.*}.1" -a 1 0 udp 60 | grep -P -o -m 1 '(?<=Mapped public port\s)\d+')
+        port=$(natpmpc -g "${vpn_gw}" -a 1 0 udp 60 | grep -P -o -m 1 '(?<=Mapped public port\s)\d+')
         if [[ -n "${port}" ]]; then
-            natpmpc -g "${vpn_gw%.*}.1" -a 1 0 tcp 60 &> /dev/null
+            natpmpc -g "${vpn_gw}" -a 1 0 tcp 60 &> /dev/null
             webui_https="http"
             if grep -q 'WebUI\\HTTPS\\Enabled=true' "${CONFIG_DIR}/config/qBittorrent.conf"; then
                 webui_https="https"
             fi
+            curl -fsSL --insecure -X POST -d "json={\"upnp\": false}" "${webui_https}://localhost:${WEBUI_PORTS%%/*}/api/v2/app/setPreferences"
             curl -fsSL --insecure -X POST -d "json={\"random_port\": false}" "${webui_https}://localhost:${WEBUI_PORTS%%/*}/api/v2/app/setPreferences"
             curl -fsSL --insecure -X POST -d "json={\"listen_port\": ${port}}" "${webui_https}://localhost:${WEBUI_PORTS%%/*}/api/v2/app/setPreferences"
-            echo "[INFO] ProtonVPN forwarded port is \"${port}\"."
+            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN forwarded port is \"${port}\"."
         else
-            echo "[WARNING] ProtonVPN port forwarding failed!"
+            echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN port forwarding failed!"
         fi
     fi
     sleep 45
