tryfix portforwarding

diff --git a/root/app/forwarded_port_update_app b/root/app/forwarded_port_update_app
--- a/root/app/forwarded_port_update_app
+++ b/root/app/forwarded_port_update_app
@@ -8,7 +8,11 @@ if grep -q 'WebUI\\HTTPS\\Enabled=true' "${CONFIG_DIR}/config/qBittorrent.conf";
     webui_https="https"
 fi
 if grep -q 'WebUI\\LocalHostAuth=false' "${CONFIG_DIR}/config/qBittorrent.conf"; then
-    curl -fsSL --insecure -X POST -d "json={\"web_ui_upnp\":false,\"upnp\":false,\"random_port\":false,\"listen_port\":${port}}" "${webui_https}://localhost:${WEBUI_PORTS%%/*}/api/v2/app/setPreferences"
+    if ! curl -fsSL --retry 5 --retry-max-time 60 --insecure -X POST -d "json={\"web_ui_upnp\":false,\"upnp\":false,\"random_port\":false,\"listen_port\":${port}}" "${webui_https}://localhost:${WEBUI_PORTS%%/*}/api/v2/app/setPreferences"; then
+        echo "[ERROR] [$(date '+%Y-%m-%d %H:%M:%S')] Unable to set forwarded port in qBittorrent, something is wrong!"
+        rm -rf "${CONFIG_DIR}/wireguard/forwarded_port"
+    fi
 else
     echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] Unable to set forwarded port in qBittorrent, \"LocalHostAuth\" is enabled!"
+    rm -rf "${CONFIG_DIR}/wireguard/forwarded_port"
 fi
